name: scribettefix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  audio_waveforms: ^1.1.1
  cloud_firestore: ^5.4.4
  dartz: ^0.10.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_background: ^1.3.0+1
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  flutter_markdown_latex: ^0.3.4
  flutter_native_splash: ^2.4.2
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^3.1.1
  flutter_sound: ^9.17.0
  flutter_svg: ^2.0.10+1
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  google_sign_in: ^6.2.1
  htmltopdfwidgets: ^1.0.5
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.0
  intl: any
  json_annotation: ^4.9.0
  markdown: ^7.2.2
  material_design_icons_flutter: ^7.0.7296
  ming_cute_icons: ^0.0.6
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  riverpod_annotation: ^2.6.1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  table_calendar: ^3.1.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.4.4
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  riverpod_lint: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"

  ios: true
  image_path: assets/splash_icon.png
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#FFFFFF"
  background_image: assets/splash_icon.png

  android_12:
    color: "#FFFFFF"
    background_image: assets/splash_icon.png